letscontrolit/ESPEasyPluginPlayground

_P104_SRF02.ino
Simple SRF02 ultrasonic range finder plugin for one sensor connected via I2C and set to default address.
=> SRF02 ultrasonic range finder plugin

_P111_SenseAir.ino
This is the first version of this plugin.
Right now only S8 sensor is supported, K30 will be added shortly.
=> SenseAir co2 sensor plugin

_P112_Power.ino
Calculate interim Wh usage until the next pulse is received.
Added a single function(Plugin_112_idleusage) which is called on "PLUGIN_READ" event.
=> Calculate temp. Wh usage.

_P211_MPU6050.ino
This plugin uses the MPU6050 accelerometer & gyro to detect motion. The motion threshold can be configured directly on the UI.
I'm currently using it to detect when my dryer and washer have finished their cycles!
=> Add MPU6050 plugin

_P149_MHZ19.ino
This patch add some controls on the MHZ19 readings (handles timeout) and reads byte per byte.
In my setup, it has greatly improved read stability of my sensor.
=> Improve MHZ19 read stability

_P131_SHT3X.ino
Very first (alpha) version of SHT30 plugin.
=> Very first (alpha) version of SHT30 plugin.

_P111_SenseAir.ino
The plugin has been completely rewritten with the following additions:
+ Support for Temperature-message
+ Support for Relative Humidity-message
+ Support for Status-message
=> Re-write of plugin 

_P111_RF.ino, _P112_RFTX.ino
Add plugin for RX/TX 433Mhz rc-switch
Thx to s4nder : [https://www.letscontrolit.com/forum/viewtopic.php?p=12486#p12486](url)
=> Add RX/TX 433Mhz rc-switch

_P142_RGB-Strip.ino
with fading and gamma correction.
stable release.
Note: ESP-software-PWM has flickering problems with values <6 and >1017. See https://github.com/esp8266/Arduino/issues/836
=> RGB and RGBW strip control

_P212_MY9291.ino
Adding this to get it out there.  Some modification is needed to the
ESPEasy Mega code to get this working.  Just adding Par4 Int to
eventStruct basically.
=> Added MY9291 (AI Light and similar WiFi RGBW bulbs)

_P150_SDM120C.ino
Still in development.
Lots to do.
=> Plugin for Eastron SDM120C Energy Meter

_P145_SDS011-Dust.ino
Dust sensor with PM2.5 and PM10 on soft serial.
Needs lib from [https://github.com/ricki-z](https://github.com/ricki-z/SDS011.git)
=> Added _P145_SDS011-Dust

_P147_DMX512.ino
Control DMX512 devices with commnad:
"DMX,5=123,22,33,44"
For more descriptions see header of file.
Status: Working and tested with actual MEGA environment
=> Added _P147_DMX512.ino

_P146_Chiming.ino
- Expand to 4 GPIOs
- Pimp GUI
- Minor bug fixes
=> _P146_Chiming.ino: Expand to 4 Bells

_P163_DS1631.ino
Hi,
This update makes plugin compatible with ESPEasy V1 and V2
=> UpDate _P163_DS1631 for ESPEasy V1 and V2 compatibility

_P162_MPL3115A2.ino
MPL3115A2 I2C Altitude Barometric Pressure Temperature Sensor
Easy to use and ok for NXP free sample.
=> MPL3115A2 I2C Altitude Pressure Temperature Sensor

_P170_HLW8012.ino
Support of HLW8012 chip for AC current/voltage reading (used in Sonoff
POW and ElectroDragon module)
=> P170 HLW8012

_P165_SerSwitch.ino
https://www.letscontrolit.com/forum/viewtopic.php?f=6&t=3245
=> Serial MCU support for Sonoff Dual and Tuya/Yewelink based wall switches

_P125_ArduCAM.ino
ArduCAM plugin for ESPEasy
The only supported device is the OV2640_MINI_2MP.
This plugin needs the library ArduCAM from:
https://github.com/ArduCAM/Arduino
=> add _P125_ArduCAM.ino

_P145_Itho.ino, libraries _PLUGIN145 ITHO FAN/Itho/CC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/CC1101.h, libraries _PLUGIN145 ITHO FAN/Itho/CC1101Packet.h, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.h, libraries _PLUGIN145 ITHO FAN/Itho/IthoPacket.h
Plugin to control ITHO: see ( https://github.com/jodur/ESPEASY_Plugin_ITHO) for more info
=> Added ITHO Plugin

_P181_TempHumidity_SHT2x.ino
Sensirion high accuracy temperature / humidity sensor (1.8% rh)
- tested, works fine for me.
=> SHT25 I2C temp/hum sensor

_P181_TempHumidity_SHT2x.ino
tested, works flawless now for about half a year.
=> SHT25 precision temp/hum sensor

_P141_LedStrip.ino
Implements a LedStrip plugin, using the amazing FastLed library :
- Controls basic RGB Led Strips
- RGB or HSV commands
- Various Animations mode
- Smooth Diming (thanks to FastLED lib)
- Rainbow color map (thanks to FastLED lib)
I will soon add support for pixel type ledstrips , and IR remote buttons.
It work well these very cheap chinese (esp8266 based) hardware :
- H801 https://www.google.fr/search?q=Huacanxing+H801&tbm=isch 
- Magic Home https://www.google.fr/search?q=magic+home+led+controller&tbm=isch
=> New Plugin : P141 LedStrip

_P118_CCS811.ino, _P130_VEML6075.ino, _P133_VL53L0X.ino
refelct changes of HTML functions form ESPEasy master and add USES_ for plugin set definitions
=> reflect changes from ESPEasy master (P130&P133)

_P183_SMA.ino
Query a SMA solar inverter using MODBUS/TCP. Get current power and daily energy
=> SMA STPx000

_P214_Atlas_EZO_pH.ino, _P215_Atlas_EZO_EC.ino
I'm looking for a water pH iot sensor since a long time, I finally found something reliable from Atlas Scientific and wrote a plugin for EspEasy in order to use this sensor easily.
I hope it will be usefull for other people.
=> Add plugin for atlas EZO pH

_P105_RGBW.ino
Updated the custom webform to implement add methods instead of appending to string. Added a sub heading for settings.
=> Webform bug fix

_P134_CSE7766.ino
Add calibration values for CSE7766 as plugin parameters. With these the internally stored initial calibration values can be overriden.
=> _P134_CSE7766 add calibration values as plugin parameters

_P134_PPD42.ino, _P135_MQ135.ino
Calculation has to be done in Celsius, so no need option to convert to Farenheit
=> Remove Temperature Conversion to Farenheit

_P141_LedStrip.ino
- Changed method calls in PLUGIN_WEBFORM_LOAD method to adhere to changed api.
- Refined text description of commands. Added additiional information and fixed two errors.
=> P141 led strip adjust to api changes

_P141_LedStrip.ino
Solving some issues. success was always set to true (Even if no command was executed). This causes some strange behavior. Add json status response to plugin.
=> Solving some issues and adding a json status response

_P198_Venta.ino
ESP8266 added on an interface PCB between control panel and main PCB - details to be published on my blog
=> P198 (Venta): Implement support for Venta LW45 humidifier

_P197_RFLink_MQTT_Bridge.ino
Add bridge plugin to send rflink data from serial pins to MQTT (raw data and parsed JSON); Also receive commands for RFLink via MQTT
=> P197: RFLink MQTT bridge

_P217_ACS712AC.ino
I wanted to add support for the ACS712 modules for AC measurement.
=> Adding support for new sensor type ACS712 for AC measurements.

_P152_MCP42010.ino
Hi.
I made a functional plugin, which corresponds to my expectations, except that ...
When I activate the plugin in device tab, I can not change the state of a GPIO anymore. I have to disable my plugin for it to work again ...
I'm using this Library : https://github.com/mensink/arduino-lib-MCP42010
Can you help me?
=> Add support for digital potentiometer : _P152_MCP42010.ino

_P176_CDM7160.ino
Add support for CDM7160 CO2 sensor.
=> Add CDM7160 CO2 sensor plugin

_P128_AS3935.ino
Add support for AS3935 Franklin Lightning Sensor™ IC by AMS
=> Add AS3935 lightning sensor plugin

_P216_PMS5003ST.ino, _P216_PMSx003ST.ino
Plantower
PMSx003ST
include:
PM2.5 TEMP HUMI HCHO
by 阿东
=> Add new sensor

P127_LibTeleinfo_Library/LibTeleinfo.cpp, P127_LibTeleinfo_Library/LibTeleinfo.h, P127_LibTeleinfo_Library/Readme.md, _P127_Teleinfo.ino
Move old part related to publishing data over a remote http endpoint.
Declare it as a two values plugin that can use controller facilities
Support both modes for our French Linky counters then older ones also.
Any review welcome especially on the LibTeleInfo dependency that I incorporated. Previous code thanks to @macgyver67 was inline and could be a better approach...but to be tested on new protocol then.
Thx,
=> Update Plugin 127: Teleinfo

_P214_Atlas_EZO_pH.ino, _P222_Atlas_EZO_ORP.ino
- No [TESTING] after One year of running perfectly
- Webserver --> web_server
=> EZO pH and ORP Sensor out of testing stage

_P201_VBAN.ino
I added a new plugin that allows to transmit the audio from an ESP32 ADC channel using the VBAN UDP audio protocol by VoiceMeeter.
=> adding P201 VBAN plugin

_P246_DAC.ino
For ESP32 only, include:
#ifdef ESP32
#ifndef USES_P246
#define USES_P246   // DAC
#endif
#endif
=> Support both ESP32 DAC outputs

_P130_VEML6075.ino, _P133_VL53L0X.ino
adapt Sensor_vType to match new scheme, see PR https://github.com/letscontrolit/ESPEasy/pull/3265
=> Adapt Sensor_vType to match new scheme,

_P145_Itho.ino, libraries _PLUGIN145 ITHO FAN/Itho/CC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/CC1101Packet.h, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.h, libraries _PLUGIN145 ITHO FAN/Itho/IthoPacket.h
Various improvements:
- Change of ISR for improved stability; Ticker was source of random crashes
- Possible to disable RF logging in plugin
- Various minor updates for compatibility with latest mega-20200410 release
More info:  https://github.com/svollebregt/ESPEASY_Plugin_ITHO and https://gathering.tweakers.net/forum/view_message/62062116
=> Itho plugin (P145) stability improvements and code changes for latest mega-20200410

_P224_DDS238.ino
Confirmed working fine with current ESPEasy builds over several days. This plugin for the DDS238-ZN kWh meters could be considered for inclusion in TESTING, on the basis that it is a less expensive alternative to the Eastron SDM120.
=> Update to work with recent builds, lifted from P085

_P145_Itho.ino, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.h
Various improvements:
- Programmable SYNC1 byte for remote
- Small cosmetic change to interface
- Updates to allow building with recent mega releases (VType)
More info and binaries: https://github.com/svollebregt/ESPEASY_Plugin_ITHO and https://gathering.tweakers.net/forum/view_message/62062116
=> Programmable SYNC1 and other minor updates

_P208_Nokia_LCD_5110.ino
- different font-sizes selectable on web-interface
- http-commands works now fine .
- http-command for backlight
- some bugs solved
=> _P208 NOKIA 5110 LCD plugin

_P111_RF.ino, _P144_RC-Switch-TX.ino
Adapt Sensor_vType to match new scheme
=> Adapt Sensor_vType to match new scheme

_P112_Power.ino
Compiles and appears functional with recent builds, but needs further testing.
=> Add Sensor_VType to enable compile with recent builds
