letscontrolit/ESPEasyPluginPlayground

_P115_HeatpumpIR.ino
Integrate the HeatpumpIR library with ESPEasy, to be able to control air conditioner / heatpump devices through infrared
=> "Heatpump IR transmitter" plugin, _P115

_P149_MHZ19.ino
Added support for MH-Z19 CO2 Sensor. 
Supported only UART connection mode for this sensor.
=> Plugin for MH-Z19 NDIR CO2 Sensor

_P123_NeoPixel_Clock.ino
A clock that uses a ring of 60 NeoPixel LEDs as display for a classic clock.
The hours are RED, the minutes are GREEN, the seconds are BLUE and the hour marks are WHITE.
The brightness of the clock hands and the hour marks can be set in the device page, or can be set by HTTP  or Rules commands. The format is as follows:
Clock,1,128,32 → 1=enable display, 128=hand brightness, 32=mark brightness
Clock,0,, → 0=disable display, without changing the saved values of the brightness
Clock,,65, → change only the brightness of the clock hands
Clock,,,10  → change only the brightness of the hour marks
=> NeoPixel Clock

_C004.ino
This update addresses some of the limitations of the Thingspeak server, such as only 8 fields are allowed to be updated and period between 2 update requests cannot be less than 15s.
Regardless of what the sensor delays are set to, every time the plugin is called it will store the most recent values from the sensor in a buffer (only for values corresponding to 8 fields in Thingspeak), and check if 15s have elapsed since last publish.
If 15s have elapsed since last publish, it will check if there is any data available in the buffer and publish it.
If no data is available in buffer then publish request is not sent.
This update eliminates the problem with multiple sensors trying to publish within 15s time period, resulting in only one publish being successful and others ignored. With this …
=> Updated Thingspeak controller plugin

_P202_ADC_ACcurrentSensor.ino
Add file: plugin _P202 to read AC current.
This is a work-in-progress. The plugin reads the mains (line) AC current via a current transformer (C.T.), currently a TA12-100 C.T. sensor, with potential to be adapted for other C.T. based sensors. 
This Plugin is an extension of the existing ADC plugin (_P002) and incorporates code from a Henry's Bench Arduino sketch to identify and record the peak current flow during the 50 or 60 Hz altenating current cyce. The Plugin also contains a number of parameters which can be configured at run-time. The value of AC current is also converted to Watts using a typical (configurable) value for AC mains (line) volts at the user's location.
=> Add file P202_ADC_ACcurrentSensor.ino

_P153_MAX44009.ino
Ambient Light Sensor with ADC that supports 22-bit dynamic range from 0.045
lux to 188,000 lux. For the device to be recognized properly by the I2C Scan, add this :
```diff
src/WebServer.ino
@@ -2194,6 +2194,8 @@ void handle_i2cscanner() {
2194  2194            break;
2195  2195          case 0x48:
2196  2196          case 0x4A:
2197 +          reply += F("MAX44009");
2198 +          break;
2197  2199          case 0x4B:
2198  2200            reply += F("PCF8591<BR>ADS1115");
2199  2201            break;
=> Added support for MAX44009 ambient light sensor

_P143_AnyonePresent.ino
The recognition of whether a person is in a room is more difficult than one often thinks. It helps if several different sensors are used (e.g., PIR, radar, light barrier, brightness, noise). However, since the sensors only emit short pulses for many pulses, many data are sent to controllers (e.g., MQTT), and the smart home system must recombine these data through complex rules to a steady "someone there".
This plugin listens for up to 3 sensors and triggers a "someone there" when a sensor responds. A "Nobody there" is not sent until all 3 sensors are silent for the set time (Presence Time). A filter prevents unwanted triggering by ESD pulses.
An analog sensor can also be connected. The absolute value of the analog voltage at AIN is irrelevant. The plugin responds to quick changes of the …
=> Added _P143_AnyonePresent.ino

_P119_BME680.ino
The BME680 sensor publishes 4 values - Temperature, Humidity, Pressure, and Gas Resistance. Unfortunately, the OpenHAB MQTT controller only publishes the first 3 values to MQTT. This pull request changes the VType to SENSOR_TYPE_QUAD which resolves the issue.
=> Fix MQTT publishing of BME680 Gas value

_P119_BME680.ino
Removed the deprecated string variable https://github.com/letscontrolit/ESPEasy/pull/1267#discussion_r182032286
Works and builds fine.
=> Removed deprecated string variable

_P135_MQ135.ino
tested using MQ135 module and wemos mini.
use MQ135 module :
https://www.amazon.com/HiLetgo-Quality-Hazardous-Detection-Arduino/dp/B00LSG5IZ2/ref=sr_1_1?ie=UTF8&qid=1525813771&sr=8-1&keywords=MQ135
circuit connectivity details :
connect MQ135 power to 5VDC and GND on wemos mini.
connect MQ135 analog output (AO) directly to ADC pin wemos mini (A0) - no external resistor.
connect MQ135 digital output (DO) to digital pin wemos mini. 
setup details :
enter recommended initial values in bracket for 'Load Resistance', 'R Zero' and 'CO2 Level ref'.
assign GPIO pin for MQ135 digital output.
leave the sensor running for 24 hours to burn in and calibrate,
then update 'rzero' when sensor is already stable.
you should get a stable CO2 value of around 400ppm in normal conditions.
for warning LED if …
=> Add MQ135 plugin

_P096_Vito.ino
Experimental Communications support for Vitotronic: 
requires VitoWifi library: https://github.com/bertmelis/VitoWiFi.
Hardware: 
- connect IR interface to RXD2/TXD2
- disable Serial in ESPEasy so the plugin can gain control over it.
Usage: This plugin does add two webpages /read and /write which are used to interface with the Vito. Use /read and /write to access data points.
Parameters for /read: 
-  &DP=0x2000 data point to read, in hex
-  &Type=TempL|TempS|CountL|CountS|Mode|Hours|CoP|Raw|all
-  &ReadLen=2 if you use Raw or all. Otherwise the number of bytes to read is derived from the data type. 
-  &MQTTTopic=vito/test untested; may require mqtt controller set up
Example: http://192.168.1.18/read?DP=0x00f8&Type=all&ReadLen=2
Parameters for /write: 
- &DP=0x2000 data point to write, …
=> Vitotronic support

_P216_LIFX.ino
Currently tested with LIFX Color 1000. 
Should work with any other LIFX lights, using UDP protocol on LAN described here:
https://lan.developer.lifx.com/docs
Example of application usage: PIR detector for elderly person to light on/off automatically, depending on current luminosity and time of the day, to adjust intensity and color. ESPEasy will also gather temp/humidity information pushed on a smart home device. Light can as well be activated over internet with the LIFX app to send "light message" to answer telephone call, or open the front door !
=> New plugin to support LIFX lights

_P218_MaxbotixEZ_Distance.ino
Add support plugin for Maxbotix Distance sensor(s).
Plugin to read distance from Maxbotix LV-MaxSonar-EZx series sensors in raw pulse width, inches, and millimeters. 
This plugin is designed to use the pulse width representation of range. This  is Pin 2 on the sensor (LV-MaxSonar-EZ0). The PWM output of the LV-EZx provides good resolution and is therefore used by this plugin rather than the serial or analog methods. The serial data would need to be decoded and thus add unnecessary complexity to the plugin. The resolution of the analog output seems (via experimentation) to be less precise than the pulse width method.
More details are in the header comments of the added _P218_ file.
=> Add Maxbotix LV MaxSonar EZx Distance Sensor plugin

_P218_SlowPWM.ino
Main reason to have slow PWN.... Sometimes we need to works with AC.
You need to get a part of period/search zero/... to make able power regulation on AC.... 
or (for slow device/heaters) control of series of periods (triac)
I use it with heater/regulator. It is incomparably better than _P021_Level to make temperature stable.
=> add regulator slow PWM

_P242_ILI9341.ino
This plugin allow to control a TFT screen (ILI9341) through HTTP API
Tested with WEMOS D1 Mini Pro and Wemos TDFT 2.4
Tested with ESPEasy 2.4.2  -tag mega-201902225)
Plugin lib_deps = Adafruit GFX, Adafruit ILI9341
This plugin is controlled by HTTP API, ie : http://<espeasy_ip>/control?cmd=tft,0,0,HelloWorld
| command | details | description |
|-----|-----|-----|
| tft | `TFT,<row>,<col>,<size=1>,<foreColor=white>,<backColor=black>,<text>` | Write text messages to TFT screen, ROW for row, COL for starting column, and Text for text. |
|tftcmd | `TFTCMD,<value=on&#124;off&#124;clear>,<clearColor=white>` | Control the screen (on, off, clear,..)|
Examples:
Write Text :
http://<espeasy_ip>/control?cmd=tft,0,0,HelloWorld
Write Text another place: …
=> Add Plugin242 : ILI9341 (TFT Display)

_P224_DDS238.ino
Pluging for Energy Meters DDS238-x ZN with MODBUS Interface (RS485), sold in Aliexpress and other similar sites usually under the brand "Hiking"
Tested with DDS238-1 ZN model, but should work with "-2" and "-4" versions as they have the same register map.
=> Plugin 224 for DDS238 Energy Meters

_P214_Atlas_EZO_pH.ino, _P222_Atlas_EZO_ORP.ino
- Name Changed from ORP EZO to EZO ORP
- Configuration of EZO pH now error tolerant. if you misconfigure a temperature correction, a temperature of 20° will be taken.
- More documentation about temperature correction for EZO pH as Note.
- Bug fix for pH calibration: if you stored a calibration for pH of e.g. 9.18 he restored 9 and you have to change it manually, now the value will be restored correctly
=> Atlas EZO pH / ORP: Minor bug fix / better documentation and renaming

_P112_Power.ino
It also did not include recent improvements of the P003 Counter plugin
on which it was originally based.
This is a fresh copy of the P003 plugin with the P112 changes added.
Furthermore, a few bugs were squashed.
A better debounce algorithm has been added.
Outputs of power and energy are now both in W and Wh units.
They are correctly scaled based on the pulses/kWh setting.
=> The old P112 Energy Counter plugin was 4 years out of date and did no longer compile.

_P224_DDS238.ino
Seems to work fine now after adding the #includes.
This plugin could be considered for inclusion within the main repository, on the basis that it is a cheaper single-DIN wide MODBUS energy meter than the SDM120.
Available via Aliexpress, see also here for technical details; http://domoticx.com/modbus-kwh-meter-dds238-1-zn/
=> [P224] Add #includes required since PR #3139

_P246_ADCfast.ino
like I said on the [Forum](https://www.letscontrolit.com/forum/viewtopic.php?f=6&t=7713&sid=ddba1d9a291fbc468401c45dc73e0068) 
I wrote a Plugin which reads the ADC 10x or 50x per Second with adjustable threshold value and
adjustable trigger (ADC >= Threshold, ADC <= Threshold, ADC == Threshold)
I have tested it myself and it seems to work like I want.
It's useful for any device which outputs a voltage (or a waveform) to detect a change immediately.
i.e. a SCT013 current sensor (to see if current flows or not. Not for measuring)
This is my first commit ever, hopefully I've done everything right :)
=> fast ADC Plugin with Threshold

_P248_AHT.ino, src/PluginStructs/P248_data_struct.cpp, src/PluginStructs/P248_data_struct.h
Added support for the AHT10, AHT20 and AHT21 sensor.
Used the P028_BME280 implementation as template to create this plugin.
Tested with ESP8266 and ESP32 using the AHT10 sensor only (AHT20 and AHT21 untested).
Additional modifications in the I2C-scanner to add detection for this sensor:
`/src/WebServer/I2C_Scanner.cpp`
`     case 0x38:`
`+      result =  F("PCF8574A,AHT10/20/21");`
`+      break;`
`    case 0x39:`
`-      result =  F("PCF8574A,TSL2561,APDS9960");`
`+      result =  F("PCF8574A,TSL2561,APDS9960,AHT10");`
=> Add support for AHT10/20/21 temperature/humidity device

_P249_GoodWeModbus.ino
I created a plugin to use the modbus possibilities of the GoodWe XS-series PV inverters. For now it has the possibility to show the most relevant numbers: total energy, day energy, feeding Watt to grid and inverter temperature. 
It looks a lot like the other modbus plugins (also the other one I created: #165, which is a bit on hold for now). It would be nice to streamline the various modbus plugins a bit, but I don't have the knowledge for that.
This plugin works for me on a recently bought (one month ago) GoodWe XS-2000 and XS-2500.
=> Plugin to read GoodWe PV Inverters with modbus/RS-485

_P145_Itho.ino, libraries _PLUGIN145 ITHO FAN/Itho/CC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/CC1101Packet.h, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.cpp, libraries _PLUGIN145 ITHO FAN/Itho/IthoCC1101.h, libraries _PLUGIN145 ITHO FAN/Itho/IthoPacket.h
Complete rework of Itho library by arjenhiemstra (https://github.com/arjenhiemstra/IthoEcoFanRFT), from his GitHub:
*  Library structure is preserved, should be a drop in replacement (apart from device id)
*  Decode incoming messages to direct usable decimals without further bit-shifting
*  DeviceID is now 3 bytes long and can be set during runtime
*  Counter2 is now the decimal sum of all bytes in decoded form from deviceType up to the last byte before counter2 subtracted from zero.
*  Encode outgoing messages in itho compatible format
*  Added ICACHE_RAM_ATTR to 'void ITHOcheck()' for ESP8266/ESP32 compatibility
*  Trigger on the falling edge and simplified ISR routine for more robust packet handling
*  Move SYNC word from 171,170 further down the message to 179,42,163,42 to filter out …
=> Updated Itho library + device ID now programmable

_P248_HomEvap.ino
I wrote a plugin for a HomEvap adiabatic cooler/humidifier. The HomEvap has a Modbus interface, which can be used to read and write values.
Currently the most important values can be read and set: duct temperature, duct humidity and the system mode:
http://<ip>/control?cmd=setduct,200 ==> duct temperature setpoint to 20 C
http://<ip>/control?cmd=sethumi,800 ==> duct humidity setpoint to 80%
http://<ip>/control?cmd=setmode,1 ==> System mode: 1=Auto, 2=Humidify, 3=Cool, 4=Off
It's my first plugin and I based the code a lot on the already existing modbus plugins available. I tested this only myself, so it would be very useful that others that have a HomEvap test it.
=> HomEvap modbus support
